/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as CampaignNewRouteImport } from './routes/campaign/new'
import { Route as CampaignCampaignIdIndexRouteImport } from './routes/campaign/$campaignId/index'
import { Route as CampaignCampaignIdSessionIdIndexRouteImport } from './routes/campaign/$campaignId/$sessionId/index'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignNewRoute = CampaignNewRouteImport.update({
  id: '/campaign/new',
  path: '/campaign/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdIndexRoute = CampaignCampaignIdIndexRouteImport.update({
  id: '/campaign/$campaignId/',
  path: '/campaign/$campaignId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdSessionIdIndexRoute =
  CampaignCampaignIdSessionIdIndexRouteImport.update({
    id: '/campaign/$campaignId/$sessionId/',
    path: '/campaign/$campaignId/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/workbench': typeof WorkbenchRoute
  '/campaign/new': typeof CampaignNewRoute
  '/settings': typeof SettingsIndexRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdIndexRoute
  '/campaign/$campaignId/$sessionId': typeof CampaignCampaignIdSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/workbench': typeof WorkbenchRoute
  '/campaign/new': typeof CampaignNewRoute
  '/settings': typeof SettingsIndexRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdIndexRoute
  '/campaign/$campaignId/$sessionId': typeof CampaignCampaignIdSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/workbench': typeof WorkbenchRoute
  '/campaign/new': typeof CampaignNewRoute
  '/settings/': typeof SettingsIndexRoute
  '/campaign/$campaignId/': typeof CampaignCampaignIdIndexRoute
  '/campaign/$campaignId/$sessionId/': typeof CampaignCampaignIdSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/workbench'
    | '/campaign/new'
    | '/settings'
    | '/campaign/$campaignId'
    | '/campaign/$campaignId/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/workbench'
    | '/campaign/new'
    | '/settings'
    | '/campaign/$campaignId'
    | '/campaign/$campaignId/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/help'
    | '/workbench'
    | '/campaign/new'
    | '/settings/'
    | '/campaign/$campaignId/'
    | '/campaign/$campaignId/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  WorkbenchRoute: typeof WorkbenchRoute
  CampaignNewRoute: typeof CampaignNewRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CampaignCampaignIdIndexRoute: typeof CampaignCampaignIdIndexRoute
  CampaignCampaignIdSessionIdIndexRoute: typeof CampaignCampaignIdSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/new': {
      id: '/campaign/new'
      path: '/campaign/new'
      fullPath: '/campaign/new'
      preLoaderRoute: typeof CampaignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/': {
      id: '/campaign/$campaignId/'
      path: '/campaign/$campaignId'
      fullPath: '/campaign/$campaignId'
      preLoaderRoute: typeof CampaignCampaignIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/$sessionId/': {
      id: '/campaign/$campaignId/$sessionId/'
      path: '/campaign/$campaignId/$sessionId'
      fullPath: '/campaign/$campaignId/$sessionId'
      preLoaderRoute: typeof CampaignCampaignIdSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  WorkbenchRoute: WorkbenchRoute,
  CampaignNewRoute: CampaignNewRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CampaignCampaignIdIndexRoute: CampaignCampaignIdIndexRoute,
  CampaignCampaignIdSessionIdIndexRoute: CampaignCampaignIdSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
